coverage:
  status:
    patch:
      default:
        target: auto
        threshold: 5%

flags:
  system:
    carryforward: true
  e2e:
    carryforward: true

ignore:
  - "**/repo/*RepositoryImpl.kt"
  - "**/repo/Fake*Repository.kt"
  - "**/OpenApiSpecTask.kt"
