coverage:
  status:
    patch:
      default:
        target: auto
        threshold: 5%

flag_management:
  individual_flags:
    - name: system
      carryforward: true
    - name: e2e
      carryforward: true

ignore:
  - "**/repo/*RepositoryImpl.kt"
  - "**/repo/Fake*Repository.kt"
  - "**/OpenApiSpecTask.kt"
