services:
  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: craftpanel
      POSTGRES_USER: craftpanel
      POSTGRES_PASSWORD: craftpanel
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data:
